config/routes.rb
Rails.application.routes.draw do

  #get 'sessions/new'

  #get 'users/show'
  #get 'users/edit'
  #get 'users/update'

  # ------------------------------------------------------------ #

  root    'single_page#index'					                  # Root_Path

  #get     '/admin',           to: 'admin_page#index'    # admin_path admin login
  #get     '/admin/about',     to: 'users#about'    # admin_about_path
  #get     '/admin/about/edit',     to: 'users#edit'    # admin_about_path
  #patch     '/admin/about/update',     to: 'users#update'    # admin_about_path
  #put     '/admin/about/update',     to: 'users#update'    # admin_about_path  

  get     '/admin',           to: 'sessions#new'        # admin_path start session login
  post    '/admin',           to: 'sessions#create'     # admin_path create session login
  delete  '/logout',          to: 'sessions#destroy'    # login_path destroy session (logout)

  scope "/admin" do
    resources :users, :only => [:show, :edit, :update]
  end
  # users_path using resouces method to obtain a full suite of RESTful routes automatically

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  before_save { self.email = email.downcase }

  validates :name,  	 presence: true, length: { maximum: 50 }
  validates :fullname, presence: true, length: { maximum: 255 }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 8 }

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

end

app/controllers/admin_page_controller.rb
class AdminPageController < ApplicationController

  # index and about can be opened if admin logged_in
  before_action :logged_in_user, only: [:index, :about]

  def index
	  	render :layout => 'application-admin'
  end

  def about
  end

  private
    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?            # If not logged_in back to admin login page and can not open all action in admin controller
        #flash[:danger] = "Please log in."
        redirect_to admin_path
      end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
      if logged_in?
        redirect_to user        # Reroute if logged_in can not going to admin login page
      else 
        render :layout => 'login-page'
      end
  end

  def create
    user = User.find_by(name: params[:session][:name])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      # flash[:danger] = 'Invalid email/password combination' # Not quite right! Create an error message.
      redirect_to :back
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to admin_path
  end

end

app/controllers/single_page_controller.rb
class SinglePageController < ApplicationController

  def index
      @users = User.all
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
      @user = User.find(params[:id])                                    # Get user by id =1 for update and edit form
      @users = User.all                                                 # Get database record to sent to layout about section
      render :layout => 'application-admin', locals: { users: @users }  # push users database record to layout about section
  end

  def about
      #@user = User.find(1)                                              # Get user by id =1 for update and edit form
      #@users = User.all                                                 # Get database record to sent to layout about section
      #render :layout => 'application-admin', locals: { users: @users }  # push users database record to layout about section
  end

  def edit
      @user = User.find(params[:id])                                    # Get user by id =1 for update and edit form
      @users = User.all                                                 # Get database record to sent to layout about section
      render :layout => 'application-admin', locals: { users: @users }  # push users database record to layout about section
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      # Handle a succesful update
      #flash[:success] = "Profile updated"
      redirect_to :back
    else
      redirect_to root_path
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      #flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:fullname)
    end

end

app/helpers/admin_page_helper.rb
module AdminPageHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	# Returns the full title on a per-page basis
	def full_title(page_title)
		base_title = "Personal App"
		if page_title.empty?
			base_title
		else 
			page_title + " | " + base_title
		end
	end

	# Returns the Admin title on a per-page basis
	def admin_title(page_title)
		base_title = "Admin Page"
		if page_title.empty?
			base_title
		else 
			page_title + " | " + base_title
		end
	end

end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end


end

app/helpers/single_page_helper.rb
module SinglePageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin_page/about.html.erb
<% provide(:title, "About") %>

<div class="row">
    <div class="col-lg-12" style="margin-top: 15px;">
        <h1 class="page-header">About-Section</h1>
    </div>
</div>
<!-- Page Head -->

<div class="row">
    <div class="col-lg-10">
        <div class="panel panel-default">
            <div class="panel-heading">
                Form
            </div>
            <div class="panel-body">
                <div class="form-group col-lg-8">
                    <%= form_for(@user) do |f| %>

                      <%= f.label :fullname %>
                      <%= f.text_field :fullname, class: 'form-control' %>
                      <br>
                      <%= f.label :title %>
                      <%= f.text_field :title, class: 'form-control' %>
                      <br>
                      <%= f.label :born_on %>
                      <%= f.date_field :born_on, class: 'form-control' %>
                      <br>
                      <%= f.label :address %>
                      <%= f.text_area :address, class: 'form-control', size: "60x3"%>
                      <br>
                      <%= f.label :zip_code %>
                      <%= f.text_field :zip_code, class: 'form-control'%>
                      <br>
                      <%= f.label :email %>
                      <%= f.email_field :email, class: 'form-control' %>
                      <br>
                      <%= f.label :phone %>
                      <%= f.telephone_field :phone, class: 'form-control' %>
                      <br>
                      <%= f.label :say_hello %>
                      <%= f.text_area :say_hello, class: 'form-control', size: "60x4" %>
                      <br>
                      <%= f.submit "Update", class: "btn btn-primary" %>

                    <% end %>
                </div>      
            </div>
        </div>
    </div>
</div>
<!-- /.row -->
<div class="row theme-color-e83b35 theme-skin-light">
    <div class="col-lg-10">
        <div class="panel panel-danger">
            <%= render 'single_page/about' %>
        </div>
    </div>
</div>
<!-- /.row -->

app/views/layouts/_footer.html.erb
<footer class="footer">
        <div class="footer-social">
            <ul class="social">
                <li><a class="ripple-centered" href="" target="_blank"><i class="rsicon rsicon-facebook"></i></a></li>
                <li><a class="ripple-centered" href="" target="_blank"><i class="rsicon rsicon-twitter"></i></a></li>
                <li><a class="ripple-centered" href="" target="_blank"><i class="rsicon rsicon-linkedin"></i></a></li>
                <li><a class="ripple-centered" href="" target="_blank"><i class="rsicon rsicon-google-plus"></i></a></li>
                <li><a class="ripple-centered" href="" target="_blank"><i class="rsicon rsicon-instagram"></i></a></li>
            </ul>
        </div>
    </footer>

app/views/layouts/_header-admin.html.erb
<div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#"><h4 style="color: #337ab7;"><strong>ADMIN - Page</strong></h4></a>
</div>
<!-- /.navbar-header -->

<ul class="nav navbar-top-links navbar-right">
    <% if logged_in? %>
    <li>
      <%=  link_to logout_path, method: "delete" do%><i class="fa fa-sign-out fa-fw"></i> Log Out<% end %>
    </li>
    <!-- put else here if there are any -->
    <% end %> 
    <!-- end logged_in user -->
</ul>
<!-- /.navbar-top-links -->

app/views/layouts/_header.html.erb
        <header class="header">
            <div class="head-bg"></div>
        
            <div class="head-bar">
                <div class="head-bar-inner">
                    <div class="row">
                        <div class="col-sm-3 col-xs-6">
                            <a class="logo" href="index.html"><span>A</span>R</a>
                        </div>
        
                        <div class="col-sm-9 col-xs-6">
                            <div class="nav-wrap">
                                <nav id="nav" class="nav">
                                    <ul class="clearfix">
                                        <li><a href="#about">About</a></li>
                                        <li><a href="#skills">Skills</a></li>
                                        <li><a href="#portfolio">Portfolio</a></li>
                                        <li><a href="#experience">Experience</a></li>
                                        <li><a href="#">Blog</a></li>
                                        <li><a href="#contact">Contact</a></li>
                                    </ul>
                                </nav>
        
                                <button class="btn-mobile btn-mobile-nav">Menu</button>
                                <button class="btn-sidebar btn-sidebar-open"><i class="rsicon rsicon-menu"></i></button>
                            </div>
                            <!-- .nav-wrap -->
                        </div>
                    </div>
                </div>
            </div>
        </header>

app/views/layouts/_nav.html.erb
<div class="mobile-nav">
        <button class="btn-mobile mobile-nav-close"><i class="rsicon rsicon-close"></i></button>
    
        <div class="mobile-nav-inner">
            <nav id="mobile-nav" class="nav">
                <ul class="clearfix">
                    <li><a href="#about">About</a></li>
                    <li><a href="#skills">Skills</a></li>
                    <li><a href="#portfolio">Portfolio</a></li>
                    <li><a href="#experience">Experience</a></li>
                    <li><a href="#">Blog</a></li>
                    <li><a href="#contact">Contact</a></li>
                </ul>
            </nav>
        </div>
    </div>

    

app/views/layouts/_sidebar-admin.html.erb
<div class="navbar-default sidebar" role="navigation" style="width: 170px;">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu"  style="margin-left: 0px;">
            <% if logged_in? %>
            <li>
                <a href="#"><i class="fa fa-user fa-fw"></i> Personal App<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level" style="margin-left: 0px;">
                    <li> <%= link_to "About", '#' %> </li>
                    <li> <%= link_to "Skills", '#' %> </li>
                    <li> <%= link_to "Portfolio", '#' %> </li>
                    <li> <%= link_to "Experience", '#' %> </li>
                    <li> <%= link_to "Education", '#' %> </li>
                    <li> <%= link_to "Tect-Section", '#' %> </li>
                    <li> <%= link_to "Interest", '#' %> </li>
                    <li> <%= link_to "Contact", '#' %> </li>
                </ul>
                <!-- /.nav-second-level -->
            </li>
            <li>
                <%=  link_to '#' do%><i class="fa fa-file fa-fw"></i> Blog<% end %>
            </li>
            <% end %>
        </ul>
    </div>
    <!-- /.sidebar-collapse -->
</div>
<!-- /.navbar-static-side -->

app/views/layouts/_sidebar.html.erb
<div class="sidebar sidebar-fixed">
        <button class="btn-sidebar btn-sidebar-close"><i class="rsicon rsicon-close"></i></button>
    
        <div class="widget-area">
            <aside class="widget widget-profile">
                <div class="profile-photo">
                    <img src="img/uploads/rs-photo-v2.jpg" alt="Anugrah Rochmat"/>
                </div>
                <div class="profile-info">
                    <h2 class="profile-title">Anugrah Rochmat</h2>
    
                    <h3 class="profile-position">Developer and Startup entrepreneur</h3>
                </div>
            </aside>
            <!-- .widget-profile -->
    
            <aside class="widget widget_search">
                <h2 class="widget-title">Search</h2>
    
                <form class="search-form">
                    <label class="ripple">
                        <span class="screen-reader-text">Search for:</span>
                        <input class="search-field" type="search" placeholder="Search">
                    </label>
                    <input type="submit" class="search-submit" value="Search">
                </form>
            </aside>
            <!-- .widget_search -->
    
            <aside class="widget widget_contact">
                <h2 class="widget-title">Contact Me</h2>
    
                <form class="rsForm" action="php/mailsender.php" method="post">
                    <div class="input-field">
                        <label>Name</label>
                        <input type="text" name="rsName" value="">
                        <span class="line"></span>
                    </div>
    
                    <div class="input-field">
                        <label>Email</label>
                        <input type="email" name="rsEmail" value="">
                        <span class="line"></span>
                    </div>
    
                    <div class="input-field">
                        <label>Subject</label>
                        <input type="text" name="rsSubject" value="">
                        <span class="line"></span>
                    </div>
    
                    <div class="input-field">
                        <label>Message</label>
                        <textarea rows="4" name="rsMessage"></textarea>
                        <span class="line"></span>
                    </div>
    
                    <span class="btn-outer btn-primary-outer ripple">
                        <input class="rsFormSubmit btn btn-lg btn-primary" type="submit" value="Send">
                    </span>
                </form>
            </aside>
            <!-- .widget_contact -->
    
            <aside class="widget widget-popuplar-posts">
                <h2 class="widget-title">Popular posts</h2>
                <ul>
                    <li>
                        <div class="post-media"><a href=""><img src="img/uploads/thumb-78x56-1.jpg" alt=""/></a></div>
                        <h3 class="post-title"><a href="">Standard Post Format With Featured Image</a></h3>
    
                        <div class="post-info"><a href=""><i class="rsicon rsicon-comments"></i>56 comments</a></div>
                    </li>
                    <li>
                        <div class="post-media"><a href=""><img src="img/uploads/thumb-78x56-2.jpg" alt=""/></a></div>
                        <h3 class="post-title"><a href="">Standard Post Format With Featured Image</a></h3>
    
                        <div class="post-info"><a href=""><i class="rsicon rsicon-comments"></i>56 comments</a></div>
                    </li>
                    <li>
                        <div class="post-media"><a href=""><img src="img/uploads/thumb-78x56-3.jpg" alt=""/></a></div>
                        <h3 class="post-title"><a href="">Standard Post Format With Featured Image</a></h3>
    
                        <div class="post-info"><a href=""><i class="rsicon rsicon-comments"></i>56 comments</a></div>
                    </li>
                </ul>
            </aside>
            <!-- .widget-popuplar-posts -->
    
            <aside class="widget widget_tag_cloud">
                <h2 class="widget-title">Tag Cloud</h2>
    
                <div class="tagcloud">
                    <a href="" title="1 topic">Business</a>
                    <a href="" title="9 topics">City</a>
                    <a href="" title="10 topics">Creative</a>
                    <a href="" title="6 topics">Fashion</a>
                    <a href="" title="2 topics">Music</a>
                    <a href="" title="5 topics">News</a>
                    <a href="" title="9 topics">Peoples</a>
                </div>
            </aside>
            <!-- .widget_tag_cloud -->
    
            <aside class="widget widget-recent-posts">
                <h2 class="widget-title">Recent posts</h2>
                <ul>
                    <li>
                        <div class="post-tag">
                            <a href="">#Photo</a>
                            <a href="">#Architect</a>
                        </div>
                        <h3 class="post-title"><a href="">Standard Post Format With Featured Image</a></h3>
    
                        <div class="post-info"><a href=""><i class="rsicon rsicon-comments"></i>56 comments</a></div>
                    </li>
                    <li>
                        <div class="post-tag">
                            <a href="">#Photo</a>
                            <a href="">#Architect</a>
                        </div>
                        <h3 class="post-title"><a href="">Standard Post Format With Featured Image</a></h3>
    
                        <div class="post-info"><a href=""><i class="rsicon rsicon-comments"></i>56 comments</a></div>
                    </li>
                    <li>
                        <div class="post-tag">
                            <a href="">#Photo</a>
                            <a href="">#Architect</a>
                        </div>
                        <h3 class="post-title"><a href="">Standard Post Format With Featured Image</a></h3>
    
                        <div class="post-info"><a href=""><i class="rsicon rsicon-comments"></i>56 comments</a></div>
                    </li>
                </ul>
            </aside>
            <!-- .widget-recent-posts -->
    
            <aside class="widget widget_categories">
                <h2 class="widget-title">Categories</h2>
                <ul>
                    <li><a href="" title="Architecture Category Posts">Architecture</a> (9)</li>
                    <li><a href="" title="Business Category Posts">Business</a> (16)</li>
                    <li><a href="" title="Creative Category Posts">Creative</a> (18)</li>
                    <li><a href="" title="Design Category Posts">Design</a> (10)</li>
                    <li><a href="" title="Development Category Posts">Development</a> (14)</li>
                    <li><a href="" title="Education Category Posts">Education</a> (9)</li>
                </ul>
            </aside>
            <!-- .widget_categories -->
        </div>
        <!-- .widget-area -->
    </div>

app/views/layouts/application-admin.html.erb
<html lang="en">

<head>
    <title><%= admin_title(yield(:title)) %></title>
    <%= favicon_link_tag 'favicon.png' %>
    
	<%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'admin_application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


</head>

<body>

    <div id="wrapper">
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0" >
            <!-- Header -->
            <%= render 'layouts/header-admin' %>
            <!-- Header -->

            <!-- Sidebar -->
            <%= render 'layouts/sidebar-admin' %>
            <!-- SIdebar -->
        </nav>

        <div id="page-wrapper" style="margin-left: 170px;">
            <%= yield %>
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->



</body>

</html>

app/views/layouts/application.html.erb
<html lang="en" class="theme-color-e83b35 theme-skin-light">
<head>
    <title><%= full_title(yield(:title)) %></title>

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- LINK CSS StyleSheet -->

      <!-- Favicon -->
      <!-- Change the picture to see it refreshed in the browser -->
      <%= favicon_link_tag 'favicon.png' %>

      <!-- Google Fonts -->
      <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Fredoka+One">
      <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:300,300italic,400,400italic,600,600italic,700,700italic,800,800italic">

      <!-- Icon Fonts -->
      <link rel="stylesheet" type="text/css" href="../fonts/map-icons/css/map-icons.min.css">
      <link rel="stylesheet" type="text/css" href="../fonts/icomoon/style.css">

      <!-- Styles -->
      <link rel="stylesheet" type="text/css" href="../js/plugins/jquery.bxslider/jquery.bxslider.css">
      <link rel="stylesheet" type="text/css" href="../js/plugins/jquery.customscroll/jquery.mCustomScrollbar.min.css">
      <link rel="stylesheet" type="text/css" href="../js/plugins/jquery.mediaelement/mediaelementplayer.min.css">
      <link rel="stylesheet" type="text/css" href="../js/plugins/jquery.fancybox/jquery.fancybox.css">
      <link rel="stylesheet" type="text/css" href="../js/plugins/jquery.owlcarousel/owl.carousel.css">
      <link rel="stylesheet" type="text/css" href="../js/plugins/jquery.owlcarousel/owl.theme.css">
      
      <!-- Modernizer for detect what features the user’s browser has to offer -->
      <script type="text/javascript" src="../js/libs/modernizr.js"></script>
</head>

<body class="home header-has-img loading">
    <!-- .mobile-nav -->
    <%= render 'layouts/nav' %>
    <!-- .mobile-nav -->
    
    <!-- .sidebar -->
    <!-- sidebar content if nav opened -->
    <%= render 'layouts/sidebar' %>
    <!-- .sidebar -->

    <div class="wrapper">
        <!-- .header -->
        <%= render 'layouts/header' %>
        <!-- .header -->
        
        <div class="content">
            <div class="container">
            <!-- START: PAGE CONTENT -->
            
            
            <!-- render it partially but still not a good practices. It's BAAAD practices -->
            <%= render 'single_page/about' %>
            <%= render 'single_page/skills' %>
            <%= render 'single_page/portfolio' %>
            <%= render 'single_page/experience' %>
            <%= render 'single_page/education' %>
            <%= render 'single_page/blog-section' %>
            <%= render 'single_page/text-section' %>
            <%= render 'single_page/interest' %>
            <%= render 'single_page/contact' %>
            
            <!-- END  : PAGE CONTENT -->
        </div> <!-- .container -->
    </div> <!-- .content -->
    
    <!-- .footer -->
    <%= render 'layouts/footer' %>
    <!-- .footer -->
  
    </div>
    <!-- .wrapper -->
    
    <a class="btn-scroll-top" href="#"><i class="rsicon rsicon-arrow-up"></i></a>
    
    <div id="overlay"></div>
    <div id="preloader">
        <div class="preload-icon"><span></span><span></span></div>
        <div class="preload-text">Loading ...</div>
    </div>
    
<!-- Scripts -->
      <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.js"></script>
      <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js"></script>
      <script type="text/javascript" src="../fonts/map-icons/js/map-icons.min.js"></script>
      <script type="text/javascript" src="../js/plugins/jquery.mousewheel-3.0.6.pack.js"></script>
      <script type="text/javascript" src="../js/plugins/imagesloaded.pkgd.min.js"></script>
      <script type="text/javascript" src="../js/plugins/isotope.pkgd.min.js"></script>
      <script type="text/javascript" src="../js/plugins/jquery.appear.min.js"></script>
      <script type="text/javascript" src="../js/plugins/jquery.onepagenav.min.js"></script>
      <script type="text/javascript" src="../js/plugins/jquery.bxslider/jquery.bxslider.min.js"></script>
      <script type="text/javascript" src="../js/plugins/jquery.customscroll/jquery.mCustomScrollbar.concat.min.js"></script>
      <script type="text/javascript" src="../js/plugins/jquery.mediaelement/mediaelement-and-player.min.js"></script>
      <script type="text/javascript" src="../js/plugins/jquery.fancybox/jquery.fancybox.pack.js"></script>
      <script type="text/javascript" src="../js/plugins/jquery.fancybox/helpers/jquery.fancybox-media.js"></script>
      <script type="text/javascript" src="../js/plugins/jquery.owlcarousel/owl.carousel.min.js"></script>
      <script type="text/javascript" src="../js/options.js"></script>
      <script type="text/javascript" src="../js/site.min.js"></script>

</body>
</html>

app/views/layouts/login-page.html.erb
<html lang="en">

<head>
    <title><%= admin_title(yield(:title)) %></title>
    <%= favicon_link_tag 'favicon.png' %>
    
  <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'admin_application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


</head>

<body>

    <div id="wrapper">
        <%= yield %>
    </div>
    <!-- /#wrapper -->



</body>

</html>

app/views/single_page/_about.html.erb
<!-- First Section / About Section in personal page-->
<section id="about" class="section section-about">
    <div class="animate-up">
        <div class="section-box">
            <div class="profile">
                <div class="row">
                    <div class="col-xs-5">
                        <div class="profile-photo"><img src="../img/uploads/rs-photo-v1.jpg" alt="Anugrah Rochmat"/></div>
                    </div>
                    <div class="col-xs-7">
                        <div class="profile-info">
                            <div class="profile-preword"><span>Hello</span></div> <% @users.each do |user| %>
                            <h1 class="profile-title"><span>I'm</span> <%= user.fullname %> </h1> 
                            <h2 class="profile-position"><%= user.title %></h2></div>
                        <ul class="profile-list">
                            <li class="clearfix">
                                <strong class="title">Age</strong>
                                <span class="cont"><%= user.born_on %></span>
                            </li>
                            <li class="clearfix">
                                <strong class="title">Address</strong>
                                <span class="cont"><%= user.address %></span>
                            </li>
                            <li class="clearfix">
                                <strong class="title">Zip Code</strong>
                                <span class="cont"><%= user.zip_code %></span>
                            </li>
                            <li class="clearfix">
                                <strong class="title">E-mail</strong>
                                <span class="cont"><a href="mailto:anugrah.rochmat@gmail.com"><%= user.email %></a></span>
                            </li>
                            <li class="clearfix">
                                <strong class="title">Phone</strong>
                                <span class="cont"><a href="#"><%= user.phone %></a></span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="profile-social">
                <ul class="social">
                    <li><a class="ripple-centered" href="https://www.facebook.com" target="_blank"><i
                            class="rsicon rsicon-facebook"></i></a></li>
                    <li><a class="ripple-centered" href="https://twitter.com" target="_blank"><i
                            class="rsicon rsicon-twitter"></i></a></li>
                    <li><a class="ripple-centered" href="https://www.linkedin.com" target="_blank"><i
                            class="rsicon rsicon-linkedin"></i></a></li>
                    <li><a class="ripple-centered" href="https://plus.google.com" target="_blank"><i
                            class="rsicon rsicon-google-plus"></i></a></li>
                    <li><a class="ripple-centered" href="https://www.instagram.com" target="_blank"><i
                            class="rsicon rsicon-instagram"></i></a></li>
                </ul>
            </div>
        </div>

<!--Say hello from me Section -->            
        <div class="section-txt-btn">
            <p><a class="btn btn-lg btn-border ripple" target="_blank"
                  href="#">Download Resume</a></p>

            <p><%= user.say_hello %></p>
        </div>
    </div>
</section>
<% end %>
<!-- #about -->

app/views/single_page/index.html.erb
<!-- will not appear because no yield in layout application.html.erb -->